apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ms-name
  name: ms-name
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ms-name
  template:
    metadata:
      labels:
        run: ms-name
    spec:
      containers:
      - name: ms-name
        image: ms-name:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080