apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:  
  name: ms-name  
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ms-name
            port:
              number: 80
            path: /